# Generated by Django 3.2.8 on 2022-11-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
