# Generated by Django 3.2.8 on 2022-11-12 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_team_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='team',
            new_name='home_team',
        ),
    ]
